
baseurl: http://www.kmpharma.in/
languageCode: en-us
title: K.M. Pharma Solution
description: K.M. Pharma Solution is high-tech company in chemical and pharmaceutical field.
theme: casper
# destination: "/Users/ashwin/workspace"
paginate: 10
# DisqusShortname: improwised
Copyright: All rights reserved - 2016
params:
  # description: "km pharma solutions"
  # cover: images/cover.png
  author: KM Pharma Solution
  # logo: images/improwised.png
  customFooterPartial: 'custom_footer.html'
